config/routes.rb
Rails.application.routes.draw do
    
  patch 'course/update_description'
  
    get 'reviews/index'

    get 'reviews/show'

    get 'reviews/new'

    get 'reviews/edit'

    get 'reviews/remove'

    get 'review/index'

    get 'review/show'

    get 'review/new'

    get 'review/edit'

    get 'review/remove'

    get 'comments/index'

    get 'comments/new'

    get 'search_tutor/index'

	get 'users/new'
    
	post 'users/new' => 'users#create'

	get 'users/index'

	get 'users/signup'

	get 'users/remove'

	get 'users/update'

	get 'users/update'

	get 'users/remove'

	get 'account/signup'

	get 'account/show_account'

	get 'account/edit_account'

	get 'account/remove_account'

	get 'home/index'

	get 'home/about'

  get 'home/blog'

    #match '/contacts',to: 'contacts#new',via: 'get'
    #post 'contacts' => 'contacts#create', :as => 'contacts'
    get 'contacts/new'
    post 'contacts' => 'contacts#create', :as => 'contacts'
    
    

  get 'admins/index'
    #resources "contacts", only: [:new, :create]

    resources :posts 
    get 'admins/index'

    get 'profiles/search'

    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    
    #general routing
    resources :users
    resources :requests
    resources :photos
    resources :comments
    
    #request routing
    resources :requests do
        collection do
            get 'allnew/:tutor_id', to: 'requests#allnew'
            post 'allnew'
        end
    end
    
    #appointment routing
    resources :appointment do
        collection do
            get 'index/:id', to: 'appointment#index'
        end
    end
    
    resources :photos
    resources :reviews
        
    root 'home#index'
	match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
    
    def index
        @user_info = User.find(session[:user_id])
        
        if @user_info.role == 2
            @calendar = Request.where("(tutorID = :id OR studentID = :id) AND isConfirmed =1", {id: session[:user_id]})
        elsif @user_info.role == 1
            @calendar = Request.where(:tutorID => session[:user_id], :isConfirmed => 1)
        else
            @calendar = Request.where(:studentID => session[:user_id], :isConfirmed => 1)
        end
        
        @agenda_student = Request.where(:studentID => session[:user_id], :isConfirmed => 1)
                            .order(:apptDate, :startTime)
                            .all.paginate(:per_page => 5, :page => params[:page])
        @agenda_tutor = Request.where(:tutorID => session[:user_id], :isConfirmed => 1)
                            .order(:apptDate, :startTime)
                            .all.paginate(:per_page => 5, :page => params[:page])
    end
    
    def edit
        @appointment = Request.find(params[:id])
    end
    
    def show
        @request = Request.find(params[:id])
    end
    
    def update
        @appointment = Request.find(params[:id])
        if @appointment.update(appointment_params)
            redirect_to :action => 'show'
        else
            render 'edit'
        end
    end
    
    def destroy
        @request = Request.find(params[:id])
        @request.destroy
        redirect_to :back
    end
    
    private
    def appointment_params
        params.require(:appointment).permit(:studentID, :tutorID, :courseID, :apptDate, :startTime, :endTime, :note)
    end

end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointment/edit.html.erb
<% @page_title = "Edit Appointment" %>

<div class="well">

<h3>Edit Appointment</h3>

<%= form_for :appointment, url: appointment_path(@appointment), method: :patch do |request| %>

<% if @appointment.errors.any? %>
    <div id="error_explanation">
        <h2>
            <%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being edited:
        </h2>
        <ul>
            <% @appointment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

<p>
    Tutor Name:     <%=User.find(@appointment.tutorID).first_name%> <%=User.find(@appointment.tutorID).last_name%><br>
    Student Name:   <%=User.find(@appointment.studentID).first_name%> <%=User.find(@appointment.studentID).last_name%><br>
    Course Name:    <%=Course.find(@appointment.courseID).course_number%>    
</p>
    
<p>
    <%= request.label :apptDate, 'Appointment Date (YYYY-MM-YY):' %><br>
    <%= request.date_field :apptDate %>
</p>

<p>
    <%= request.label :startTime, 'Start Time:' %><br>
    <%= request.time_field :startTime %>
</p>

<p>
    <%= request.label :endTime, 'End Time:' %><br>
    <%= request.time_field :endTime %>
</p>

<p>
    <%= request.label :note, 'Special Request (Notes):' %><br>
    <%= request.text_area :note, cols: "60", rows: "10" %>
</p>

<p>
    <%= request.submit :class => 'btn btn-info' %>
</p>

<%= link_to 'Back', :back, :class => 'btn btn-primary' %>

<% end %>
    
</div>

app/views/appointment/index.html.erb
<% @page_title = "My Appointments" %>
<div class="well">
 
<!--======================    RENDER CALENDAR    ======================-->

    <h3>My Calendar</h3>
    <%= month_calendar events: @calendar do |date, meetings| %>
    <%= date.day %>
      <% meetings.each do |meeting| %>
        <div>
            <% if meeting.tutorID == session[:user_id] && ( @user_info.role == 1 || @user_info.role == 2 ) %>
                <%= link_to appointment_path(meeting) do %>
                    <%= meeting.startTime.strftime("%I:%M%p") %> - <%= meeting.endTime.strftime("%I:%M%p") %>
                    [Teaching]
                    <%= User.find(meeting.studentID).first_name %>
                    <%= Course.find(meeting.courseID).course_number %>
                <% end %>
            <% else %>
                <%= link_to appointment_path(meeting) do %>
                    <%= meeting.startTime.strftime("%I:%M%p") %> - <%= meeting.endTime.strftime("%I:%M%p") %>
                    [Learning]
                    <%= User.find(meeting.tutorID).first_name %>
                    <%= Course.find(meeting.courseID).course_number %>
                <% end %>
            <%end%>
        </div>
      <% end %>
    <% end %>
    
<!--======================    TUTORING AGENDA    ======================-->
    <% if @user_info.role == 1 || @user_info.role == 2 %>
    <h3>My Appointments (As Tutor)</h3>
    <div class="table-responsive .col-lg-7">
          <table class="table" summary="Appointments" >
            <tr>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Student Name</th>
                <th>Course Name</th>
                <th>Notes</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <% @agenda_tutor.each do |appointment| %>
            <% course = Course.find(appointment.courseID)%>
            <% user = User.find(appointment.studentID)%>
                <tr>
                    <td><%= appointment.apptDate %></td>
                    <td><%= appointment.startTime.strftime("%I:%M%p") %></td>
                    <td><%= appointment.endTime.strftime("%I:%M%p") %></td>
                    <td><%= user.first_name %> <%= user.last_name %></td>
                    <td><%= course.course_number %></td>
                    <td><%= appointment.note %></td>    
                    <td><%= link_to 'Show', appointment_path(appointment) %></td>
                    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
                    <td><%= link_to 'Cancel', request_path(appointment), method: :delete,
                        data: { confirm: 'Cancelling appointment. Are you sure?' } %>
                    </td>
                </tr>
            <% end %>
          </table>
        <%= will_paginate @agenda_tutor %>
    </div>
    <div class="col-sm4"></div>
    <div class="col-sm4"></div>
    <%end%>
    
<!--======================    STUDENT AGENDA    ======================-->
    <% if @user_info.role == 0 || @user_info.role == 2 %>
    <h3>My Appointments (As Student)</h3>
    <div class="table-responsive .col-lg-7">
          <table class="table" summary="Appointments" >
            <tr>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Tutor Name</th>
                <th>Course Name</th>
                <th>Notes</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            <% @agenda_student.each do |appointment| %>
            <% course = Course.find(appointment.courseID)%>
            <% user = User.find(appointment.tutorID)%>
                <tr>
                    <td><%= appointment.apptDate %></td>
                    <td><%= appointment.startTime.strftime("%I:%M%p") %></td>
                    <td><%= appointment.endTime.strftime("%I:%M%p") %></td>
                    <td><%= user.first_name %> <%= user.last_name %></td>
                    <td><%= course.course_number %></td>
                    <td><%= appointment.note %></td>    
                    <td><%= link_to 'Show', appointment_path(appointment) %></td>
                    <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
                    <td><%= link_to 'Cancel', request_path(appointment), method: :delete,
                        data: { confirm: 'Cancelling appointment. Are you sure?' } %>
                    </td>
                </tr>
            <% end %>
          </table>
        <%= will_paginate @agenda_student %>
    </div>
    <div class="col-sm4"></div>
    <div class="col-sm4"></div>
    <%end%>
    
</div>

app/views/appointment/show.html.erb
<div class="well">

    <h3>Appointment Request</h3>

    <p>
    <strong>Tutor Name:</strong>
        <%= User.find(@request.tutorID).first_name %> <%= User.find(@request.tutorID).last_name %>
    </p>

    <p>
    <strong>Student Name:</strong>
        <%= User.find(@request.studentID).first_name %> <%= User.find(@request.studentID).last_name %>
    </p>

    <p>
    <strong>Course Name:</strong>
        <%= Course.find(@request.courseID).course_number %>
    </p>

    <p>
    <strong>Appointment Date:</strong>
        <%= @request.apptDate %>
    </p>

    <p>
    <strong>Start Time:</strong>
        <%= @request.startTime.strftime("%I:%M%p") %>
    </p>

    <p>
    <strong>End Time:</strong>
        <%= @request.endTime.strftime("%I:%M%p") %>
    </p>

    <p>
    <strong>Note:</strong>
        <%= @request.note %>
    </p>

    <%= link_to 'Edit Details', edit_appointment_path(@request) %> |
    <%= link_to 'Back', :action => 'index', :id => session[:user_id] %>
    
</div>