config/routes.rb
Rails.application.routes.draw do
    
  patch 'course/update_description'
  
    get 'reviews/index'

    get 'reviews/show'

    get 'reviews/new'

    get 'reviews/edit'

    get 'reviews/remove'

    get 'review/index'

    get 'review/show'

    get 'review/new'

    get 'review/edit'

    get 'review/remove'

    get 'comments/index'

    get 'comments/new'

    get 'search_tutor/index'

	get 'users/new'
    
	post 'users/new' => 'users#create'

	get 'users/index'

	get 'users/signup'

	get 'users/remove'

	get 'users/update'

	get 'users/update'

	get 'users/remove'

	get 'account/signup'

	get 'account/show_account'

	get 'account/edit_account'

	get 'account/remove_account'

	get 'home/index'

	get 'home/about'

  get 'home/blog'

    #match '/contacts',to: 'contacts#new',via: 'get'
    #post 'contacts' => 'contacts#create', :as => 'contacts'
    get 'contacts/new'
    post 'contacts' => 'contacts#create', :as => 'contacts'
    
    

  get 'admins/index'
    #resources "contacts", only: [:new, :create]

    resources :posts 
    get 'admins/index'

    get 'profiles/search'

    resources :comments, only: [:index, :create]
    get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
    
    #general routing
    resources :users
    resources :requests
    resources :photos
    resources :comments
    
    #request routing
    resources :requests do
        collection do
            get 'allnew/:tutor_id', to: 'requests#allnew'
            post 'allnew'
        end
    end
    
    #appointment routing
    resources :appointment do
        collection do
            get 'index/:id', to: 'appointment#index'
        end
    end
    
    resources :photos
    resources :reviews
        
    root 'home#index'
	match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/request.rb
class Request < ActiveRecord::Base
    
    alias_attribute :start_time, :apptDate

    #----------------------------------------
    validates :tutorID, presence: true
    validates :studentID, presence: true
    validates :courseID, presence: true
    validates :apptDate, presence: true
    validates :startTime, presence: true
    validates :endTime, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
    
    def pending
        @requests = Request.where(:tutorID => session[:user_id], :isConfirmed => 0).order(:apptDate, :startTime).all
        @numRequests = Request.where(:tutorID => session[:user_id], :isConfirmed => 0).count
        if !Request.exists?(:tutorID => session[:user_id], :isConfirmed => 0)
            flash.now[:notice] = "You don't have any pending appointment request at the moment."
        end
    end
    
    def confirm
        @request = Request.find(params[:id])
        @request.update_attribute(:isConfirmed, 1)
        redirect_to action: 'pending', :id => session[:user_id]
    end
    
    def show
        @request = Request.find(params[:id])
    end
    
    def allnew
        user = User.find(params[:user_id])
        if  (user.id == session[:user_id] &&
             params[:user_id] != params[:tutor_id] &&
             User.where(:id => params[:user_id]).exists? &&
             User.where(:id => params[:tutor_id]).exists? && 
             User.where(:id => params[:tutor_id]).first.role != 0)
            
            @tutor_cours = CourseTutor.select("*").joins(:course).where(:user_id => params[:tutor_id]).all
            @request = Request.new(tutorID: params[:tutor_id])
        else
            flash[:notice] = "Can not submit this request!(Course must be selected)!"
            redirect_to(:back)
        end
    end
    
    def new
        @request = Request.new(tutorID: params[:tutor_id], courseID: params[:cours_id])
    end
    
    def edit
        @request = Request.find(params[:id])
    end
    
    def create
        user = User.find(request_params[:studentID])
        tutor = User.find(request_params[:tutorID])
        
        @request = Request.new(request_params)
        if  (user.id == session[:user_id] &&
             user.id != tutor.id &&
             User.where(:id => user.id).exists? &&
             User.where(:id => tutor.id).exists? && 
             Course.where(:id => request_params[:courseID]).exists? && 
             User.where(:id => tutor.id).first.role != 0)
        
            if @request.save
                flash[:notice] = "Your request was created successfully!"
                redirect_to :controller => 'profiles', :action => 'index', :id => session[:user_id]
            else
                render 'new'
            end
        else
            flash[:notice] = "Can not create this request Nice Try!"
            redirect_to(:back)
        end
    end
    
    def update
        @request = Request.find(params[:id])
        if @request.update(request_params)
            redirect_to @request
        else
            render 'edit'
        end
    end
    
    def destroy
        @request = Request.find(params[:id])
        @request.destroy
        redirect_to :back
    end
    
    private
    def request_params
        params.require(:request).permit(:studentID, :tutorID, :courseID, :apptDate, :startTime, :endTime, :note)
    end
    
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_for @request do |request| %>
 
<% if @request.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@request.errors.count, "error") %> prohibited this request from being sent:
    </h2>
    <ul>
        <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<p>
    <%= request.hidden_field :tutorID, :value => @tutor_id %>
</p>

<p>
    <%= request.hidden_field :studentID, :value => @user_id %>
</p>

<p>
    <%= request.label :courseID, 'Course ID:' %><br>
    <%= request.text_field :courseID %>
</p>

<p>
    <%= request.label :apptDate, 'Appointment Date (YYYY-MM-YY):' %><br>
    <%= request.date_field :apptDate %>
</p>

<p>
    <%= request.label :startTime, 'Start Time:' %><br>
    <%= request.time_field :startTime %>
</p>

<p>
    <%= request.label :endTime, 'End Time:' %><br>
    <%= request.time_field :endTime %>
</p>

<p>
    <%= request.label :note, 'Special Request (Notes):' %><br>
    <%= request.text_area :note %>
</p>

<p>
    <%= request.submit %>
</p>

<% end %>

app/views/requests/allnew.html.erb
<% @page_title = "Appointment Request" %>
<div class="well">

<h3>Appointment Request</h3>

<%= form_for @request do |request| %>
 
<% if @request.errors.any? %>
<div id="error_explanation">

        <%= pluralize(@request.errors.count, "error") %> prohibited this request from being sent:

    <ul>
        <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<p>
    <%= request.hidden_field :tutorID%>
</p>

<p>
    <%= request.hidden_field :studentID, :value => session[:user_id] %>
</p>

<p>
    <%= request.label :courseID, 'Course Name: (Select one of the available course from this tutor)' %><br>
    <%= request.collection_select :courseID, @tutor_cours, :course_id, :course_number, :prompt => "Select a course" %>
</p>
    
<p>
    <%= request.label :apptDate, 'Appointment Date (YYYY-MM-YY):' %><br>
    <%= request.text_field :apptDate %>
</p> 
    
<p>
    <%= request.label :startTime, 'Start Time:' %><br>
    <%= request.text_field :startTime %>
</p>
    
<p>
    <%= request.label :endTime, 'End Time:' %><br>
    <%= request.text_field :endTime %>
</p>

<p>
    <%= request.label :note, 'Special Request (Notes):' %><br>
    <%= request.text_area :note, cols: "60", rows: "10" %>
</p>

<p>
    <%= request.submit :class => 'btn btn-info' %>
</p>

<%= link_to(:controller => 'profiles', :action => 'index', :id => session[:user_id]) do %><div class="btn btn-primary">Go Back</div><% end %>

<% end %>
    
</div>

app/views/requests/edit.html.erb
<% @page_title = "Edit Request" %>
<div class="well">

<h3>Edit Appointment
</h3>

<%= form_for :request, url: request_path(@request), method: :patch do |request| %>

<% if @request.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@request.errors.count, "error") %> prohibited this request from being sent:
    </h2>
    <ul>
        <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<p>
    Tutor Name:     <%=User.find(@request.tutorID).first_name%> <%=User.find(@request.tutorID).last_name%><br>
    Student Name:   <%=User.find(@request.studentID).first_name%> <%=User.find(@request.studentID).last_name%><br>
    Course Name:    <%=Course.find(@request.courseID).course_number%>    
</p>
    
<p>
    <%= request.label :apptDate, 'Appointment Date (YYYY-MM-YY):' %><br>
    <%= request.date_field :apptDate %>
</p>

<p>
    <%= request.label :startTime, 'Start Time:' %><br>
    <%= request.time_field :startTime %>
</p>

<p>
    <%= request.label :endTime, 'End Time:' %><br>
    <%= request.time_field :endTime %>
</p>

<p>
    <%= request.label :note, 'Special Request (Notes):' %><br>
    <%= request.text_area :note, cols: "60", rows: "10" %>
</p>

<p>
    <%= request.submit :class => 'btn btn-info' %>
</p>

<%= link_to 'Back', :back, :class => 'btn btn-primary' %>

<% end %>
    
</div>

app/views/requests/index.html.erb
<% @page_title = "Appointment Request" %>
<div class="well">

<h3>Pending Appointment Requests</h3>
    <div class="row">
        <div class="table-responsive .col-lg-7">
          <table class="table table-bordered " summary="Student course list" >
            <tr>
                <th></th>
                <th>TutorID</th>
                <th>StudentID</th>
                <th>CourseID</th>
                <th>Appointment Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Notes</th>
                <th></th>
                <th></th>
            </tr>
            <% @requests.each do |request| %>
            <tr>
                <td>
                    <%= link_to 'Cancel', request_path(request), method: :delete, data: { confirm: 'Are you sure?' } %> 
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </td>
                <td><%= request.tutorID %></td>
                <td><%= request.studentID %></td>
                <td><%= request.courseID %></td>
                <td><%= request.apptDate %></td>
                <td><%= request.startTime.strftime("%I:%M%p") %></td>
                <td><%= request.endTime.strftime("%I:%M%p") %></td>        
                <td><%= request.note %></td>    
                <td><%= link_to 'Show', request_path(request) %></td>
                <td><%= link_to 'Edit', edit_request_path(request) %></td>
            </tr>
            <% end %>
          </table>
        </div>
        <div class="col-sm4"></div>
        <div class="col-sm4"></div>
    </div>
    
</div>

app/views/requests/new.html.erb
<% @page_title = "Appointment Request" %>
<div class="well">

    <h3>Appointment Request</h3>

<%= form_for @request do |request| %>
 
<% if @request.errors.any? %>
<div id="error_explanation">
       
        <%= pluralize(@request.errors.count, "error") %> prohibited this request from being sent:
    <ul>
        <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<p>
    <%= request.hidden_field :tutorID %>
</p>

<p>
    <%= request.hidden_field :studentID, :value => session[:user_id] %>
</p>

<p>
    <%= request.hidden_field :courseID %>
</p>

<p>
    <%= request.label :apptDate, 'Appointment Date (YYYY-MM-YY):' %><br>
    <%= request.date_field :apptDate %>
</p>

<p>
    <%= request.label :startTime, 'Start Time:' %><br>
    <%= request.time_field :startTime %>
</p>

<p>
    <%= request.label :endTime, 'End Time:' %><br>
    <%= request.time_field :endTime %>
</p>

<p>
    <%= request.label :note, 'Special Request (Notes):' %><br>
    <%= request.text_area :note, cols: "60", rows: "10" %>
</p>

<p>
    <%= request.submit :class => 'btn btn-info' %>
</p>

<%= link_to 'Back', :back, :class => 'btn btn-primary' %>

<% end %>
    
</div>

app/views/requests/pending.html.erb
<% @page_title = "Pending Requests" %>
<div class="well">
<h3>You have <%= @numRequests %> Pending Appointment Requests</h3>
<div class="table-responsive .col-lg-7">
  <table class="table" summary="Pending Appointment Requests" >
    <tr>
        <th>Appointment Date</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Student Name</th>
        <th>Course Name</th>
        <th>Notes</th>
        <th></th>
        <th></th>
    </tr>
    <% @requests.each do |request| %>
    <% course = Course.find(request.courseID)%>
    <% user = User.find(request.studentID)%>
    <tr>
        <td><%= request.apptDate %></td>
        <td><%= request.startTime.strftime("%I:%M%p") %></td>
        <td><%= request.endTime.strftime("%I:%M%p") %></td>
        <td><%= user.first_name %> <%= user.last_name %></td>
        <td><%= course.course_number %></td>
        <td><%= request.note %></td>    
        <td><%= link_to 'Accept', request_path(request) %></td>
        <td><%= link_to 'Ignore', request_path(request), method: :delete,
            data: { confirm: 'Ignored request will be removed permanently. Are you sure?' } %>
        </td>
    </tr>
    <% end %>
  </table>
</div>
<div class="col-sm4"></div>
<div class="col-sm4"></div>
</div>

app/views/requests/show.html.erb
<div class="well">

    <h3>Appointment Request</h3>

    <p>
    <strong>Tutor Name:</strong>
        <%= User.find(@request.tutorID).first_name %> <%= User.find(@request.tutorID).last_name %>
    </p>

    <p>
    <strong>Student Name:</strong>
        <%= User.find(@request.studentID).first_name %> <%= User.find(@request.studentID).last_name %>
    </p>

    <p>
    <strong>Course Name:</strong>
        <%= Course.find(@request.courseID).course_number %>
    </p>

    <p>
    <strong>Appointment Date:</strong>
        <%= @request.apptDate %>
    </p>

    <p>
    <strong>Start Time:</strong>
        <%= @request.startTime.strftime("%I:%M%p") %>
    </p>

    <p>
    <strong>End Time:</strong>
        <%= @request.endTime.strftime("%I:%M%p") %>
    </p>

    <p>
    <strong>Note:</strong>
        <%= @request.note %>
    </p>

    <%= link_to 'Edit Details', edit_request_path(@request) %> |
    <%= link_to 'Accept Request', :action => 'confirm', :id => @request.id %> |
    <%= link_to 'Back', :action => 'pending', :id => session[:user_id] %>
    
</div>